import type { Action, Prospect } from './types';

/* Seed data — used on first load. After that, the hub persists
   user changes in localStorage. */

export const MISSION =
  "Tell CRE lenders, title teams, brokers, and sponsors which commercial projects just moved — before the market catches up.";

export const LAUNCH_DATE = '2026-05-05'; // day 1
export const PLAN_LENGTH_DAYS = 90;

export const GOALS_90D: { label: string; week: number }[] = [
  { label: 'LLC filed, bank open, domain live', week: 1 },
  { label: '200-prospect list built', week: 2 },
  { label: '5 verbal commits', week: 4 },
  { label: 'First 5 paying customers', week: 6 },
  { label: 'Tulsa scraper live + first auto digest', week: 8 },
  { label: '$1,500 MRR', week: 13 },
];

export const SEED_ACTIONS: Action[] = [
  {
    id: 'a1',
    who: 'Madison',
    text: 'Send 20 cold emails to Tulsa CRE lenders + title teams + brokers',
    done: false,
    priority: 'high',
  },
  {
    id: 'a2',
    who: 'Madison',
    text: 'Triage replies from yesterday',
    done: false,
    priority: 'high',
  },
  {
    id: 'a3',
    who: 'Madison',
    text: 'Add 15 new prospects to pipeline',
    done: false,
    priority: 'med',
  },
  {
    id: 'a4',
    who: 'Jason',
    text: 'File Vantage LLC w/ OK Secretary of State',
    done: false,
    priority: 'high',
  },
  {
    id: 'a5',
    who: 'Jason',
    text: 'Lock domain + point at Vercel',
    done: false,
    priority: 'high',
  },
  {
    id: 'a6',
    who: 'Jason',
    text: 'Hub review — push prospect stages forward',
    done: false,
    priority: 'med',
  },
];

export const SEED_PROSPECTS: Prospect[] = [
  {
    id: 'p1',
    company: 'BOK Financial Commercial Real Estate',
    contactName: 'Eric Ramos',
    role: 'Senior CRE Lender',
    email: 'eramos@bokf.com',
    phone: '(918) 555-0188',
    metro: 'Tulsa',
    segment: 'Commercial lender',
    stage: 'cold',
    lastTouchAt: '',
    nextAction: 'Send lender permit-signal email',
    owner: 'Madison',
  },
  {
    id: 'p2',
    company: 'Titan Title & Closing',
    contactName: 'Kara Michaels',
    role: 'Commercial Escrow Officer',
    email: 'kara@titantitle.com',
    phone: '(918) 555-0233',
    metro: 'Tulsa',
    segment: 'Title / closing',
    stage: 'cold',
    lastTouchAt: '',
    nextAction: 'Cold email + LinkedIn touch',
    owner: 'Madison',
  },
  {
    id: 'p3',
    company: 'Paradigm Realty Advisors',
    contactName: 'Dave Cocolin',
    role: 'CEO',
    email: 'dcocolin@paradigmra.com',
    metro: 'Tulsa',
    segment: 'CRE broker',
    stage: 'cold',
    lastTouchAt: '',
    nextAction: 'Warm intro prep',
    owner: 'Jason',
  },
  {
    id: 'p4',
    company: 'First Oklahoma Bank CRE Lending',
    contactName: 'Diane Pfeiffer',
    role: 'VP Commercial Banking',
    email: 'dpfeiffer@firstokbank.com',
    metro: 'Tulsa',
    segment: 'Commercial lender',
    stage: 'cold',
    lastTouchAt: '',
    nextAction: 'Cold email',
    owner: 'Madison',
  },
  {
    id: 'p5',
    company: 'FirsTitle Commercial Services',
    contactName: 'Megan Hill',
    role: 'Business Development',
    email: 'mhill@firstitle.com',
    metro: 'Tulsa',
    segment: 'Title / closing',
    stage: 'cold',
    lastTouchAt: '',
    nextAction: 'Send title pipeline email',
    owner: 'Madison',
  },
  {
    id: 'p6',
    company: 'Stan Johnson Co.',
    contactName: 'Lacey Whitcomb',
    role: 'Commercial Broker',
    email: 'lwhitcomb@stanjohnsonco.com',
    metro: 'Tulsa',
    segment: 'CRE broker',
    stage: 'cold',
    lastTouchAt: '',
    nextAction: 'Cold email',
    owner: 'Madison',
  },
  {
    id: 'p7',
    company: 'Riverbend Development Partners',
    contactName: 'Aaron Boyd',
    role: 'Managing Partner',
    email: 'aaron@riverbenddev.com',
    metro: 'Tulsa',
    segment: 'Sponsor / borrower',
    stage: 'cold',
    lastTouchAt: '',
    nextAction: 'Warm intro via Jason',
    owner: 'Jason',
  },
  {
    id: 'p8',
    company: 'Tulsa Office Partners',
    contactName: 'Karen Estrella',
    role: 'Development Manager',
    email: 'kestrella@tulsaofficepartners.com',
    metro: 'Tulsa',
    segment: 'Developer',
    stage: 'cold',
    lastTouchAt: '',
    nextAction: 'Cold email',
    owner: 'Madison',
  },
];
