"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import {
  ClipboardCopy,
  Check,
  FileText,
  Thermometer,
  Droplets,
  Cloud,
  AlertTriangle,
  ChevronDown,
  ChevronUp,
} from "lucide-react";

interface EODData {
  date: string;
  jobCount: number;
  totalSets: number;
  totalBF: number;
  avgYield: number;
  yieldPercent: number;
  target: number;
  weather: { temp: number; humidity: number; conditions: string };
  problems: string[];
  jobs: {
    id: string;
    location: string;
    setsUsed: number | null;
    boardFeet: number | null;
    yieldActual: number | null;
    jobType: string | null;
    substrate: string | null;
    problems: string[];
  }[];
}

function formatDate(dateStr: string): string {
  const d = new Date(dateStr + "T12:00:00");
  return d.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}

function formatNumber(n: number): string {
  return n.toLocaleString("en-US");
}

export default function EODReport() {
  const [data, setData] = useState<EODData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [jobsExpanded, setJobsExpanded] = useState(false);

  useEffect(() => {
    const today = new Date().toISOString().split("T")[0];
    fetch(`/api/eod-report?date=${today}`)
      .then((r) => r.json())
      .then((d) => {
        if (d.success) {
          setData(d.data);
        } else {
          setError(d.error?.message || "Failed to load report");
        }
      })
      .catch(() => setError("Network error"))
      .finally(() => setLoading(false));
  }, []);

  const buildClipboardText = (d: EODData): string => {
    const lines = [
      "FoamDial Pro \u2014 Daily Report",
      `Date: ${formatDate(d.date)}`,
      `Jobs: ${d.jobCount} | Sets: ${d.totalSets} | Board Feet: ${formatNumber(d.totalBF)}`,
      `Avg Yield: ${formatNumber(d.avgYield)} bf/set (${d.yieldPercent}% of target)`,
      `Weather: ${d.weather.temp}\u00B0F, ${d.weather.humidity}% RH, ${d.weather.conditions}`,
      `Issues: ${d.problems.length > 0 ? d.problems.join(", ") : "None"}`,
      "---",
      "Generated by FoamDial Pro",
    ];
    return lines.join("\n");
  };

  const handleCopy = async () => {
    if (!data) return;
    try {
      await navigator.clipboard.writeText(buildClipboardText(data));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = buildClipboardText(data);
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const container = {
    hidden: { opacity: 0 },
    show: { opacity: 1, transition: { staggerChildren: 0.08 } },
  };
  const item = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0 },
  };

  if (loading) {
    return (
      <div className="glass-card p-8 text-center">
        <div className="animate-pulse text-white/30 text-sm">
          Generating end-of-day report...
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="glass-card p-8 text-center">
        <AlertTriangle className="w-6 h-6 text-red-400 mx-auto mb-2" />
        <div className="text-sm text-red-400">{error}</div>
      </div>
    );
  }

  if (!data) return null;

  const yieldColor =
    data.yieldPercent >= 95
      ? "text-green-400"
      : data.yieldPercent >= 85
      ? "text-yellow-400"
      : "text-red-400";

  const yieldBg =
    data.yieldPercent >= 95
      ? "bg-green-400/10 border-green-400/20"
      : data.yieldPercent >= 85
      ? "bg-yellow-400/10 border-yellow-400/20"
      : "bg-red-400/10 border-red-400/20";

  return (
    <motion.div
      variants={container}
      initial="hidden"
      animate="show"
      className="space-y-5"
    >
      {/* Header */}
      <motion.div variants={item} className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-orange/15 border border-orange/20 flex items-center justify-center">
            <FileText className="w-5 h-5 text-orange" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-white tracking-tight">
              End-of-Day Report
            </h2>
            <p className="text-xs text-white/40">{formatDate(data.date)}</p>
          </div>
        </div>
        <button
          onClick={handleCopy}
          className="btn-glass px-4 py-2 rounded-xl text-sm flex items-center gap-2 hover:border-orange/30 transition-all"
        >
          {copied ? (
            <>
              <Check className="w-4 h-4 text-green-400" />
              <span className="text-green-400">Copied</span>
            </>
          ) : (
            <>
              <ClipboardCopy className="w-4 h-4 text-white/50" />
              <span className="text-white/60">Copy to Clipboard</span>
            </>
          )}
        </button>
      </motion.div>

      {/* Stats grid */}
      <motion.div
        variants={item}
        className="grid grid-cols-2 lg:grid-cols-4 gap-3"
      >
        {/* Jobs */}
        <div className="glass-card p-4">
          <div className="text-xs text-white/40 mb-1">Jobs Today</div>
          <div className="text-2xl font-bold text-white">{data.jobCount}</div>
        </div>

        {/* Sets */}
        <div className="glass-card p-4">
          <div className="text-xs text-white/40 mb-1">Total Sets</div>
          <div className="text-2xl font-bold text-white">{data.totalSets}</div>
        </div>

        {/* Board Feet */}
        <div className="glass-card p-4">
          <div className="text-xs text-white/40 mb-1">Board Feet</div>
          <div className="text-2xl font-bold text-white">
            {formatNumber(data.totalBF)}
          </div>
        </div>

        {/* Avg Yield */}
        <div className={`glass-card p-4 border ${yieldBg}`}>
          <div className="text-xs text-white/40 mb-1">Avg Yield</div>
          <div className={`text-2xl font-bold ${yieldColor}`}>
            {formatNumber(data.avgYield)}
          </div>
          <div className={`text-xs mt-0.5 ${yieldColor}`}>
            {data.yieldPercent}% of target
          </div>
        </div>
      </motion.div>

      {/* Weather bar */}
      <motion.div variants={item} className="glass-card p-4">
        <div className="text-xs text-white/40 mb-3 uppercase tracking-wider">
          Weather Conditions
        </div>
        <div className="flex flex-wrap gap-5">
          <div className="flex items-center gap-2">
            <Thermometer className="w-4 h-4 text-orange/70" />
            <span className="text-sm text-white/80">
              {data.weather.temp}&deg;F
            </span>
          </div>
          <div className="flex items-center gap-2">
            <Droplets className="w-4 h-4 text-blue-400/70" />
            <span className="text-sm text-white/80">
              {data.weather.humidity}% RH
            </span>
          </div>
          <div className="flex items-center gap-2">
            <Cloud className="w-4 h-4 text-white/40" />
            <span className="text-sm text-white/80">
              {data.weather.conditions}
            </span>
          </div>
        </div>
      </motion.div>

      {/* Issues */}
      <motion.div variants={item} className="glass-card p-4">
        <div className="text-xs text-white/40 mb-2 uppercase tracking-wider">
          Issues Flagged
        </div>
        {data.problems.length === 0 ? (
          <div className="flex items-center gap-2">
            <Check className="w-4 h-4 text-green-400" />
            <span className="text-sm text-green-400">
              No issues reported today
            </span>
          </div>
        ) : (
          <div className="flex flex-wrap gap-2">
            {data.problems.map((p) => (
              <span
                key={p}
                className="px-3 py-1 rounded-lg bg-red-400/10 border border-red-400/20 text-xs text-red-400"
              >
                {p}
              </span>
            ))}
          </div>
        )}
      </motion.div>

      {/* Job breakdown (collapsible) */}
      {data.jobs.length > 0 && (
        <motion.div variants={item} className="glass-card overflow-hidden">
          <button
            onClick={() => setJobsExpanded(!jobsExpanded)}
            className="w-full p-4 flex items-center justify-between hover:bg-white/[0.02] transition-colors"
          >
            <span className="text-xs text-white/40 uppercase tracking-wider">
              Job Breakdown ({data.jobs.length})
            </span>
            {jobsExpanded ? (
              <ChevronUp className="w-4 h-4 text-white/30" />
            ) : (
              <ChevronDown className="w-4 h-4 text-white/30" />
            )}
          </button>
          {jobsExpanded && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              exit={{ opacity: 0, height: 0 }}
              className="border-t border-white/[0.06]"
            >
              {data.jobs.map((job) => {
                const probs = Array.isArray(job.problems) ? job.problems : [];
                const hasIssues = probs.some(
                  (p) => p && p !== "None"
                );
                return (
                  <div
                    key={job.id}
                    className="p-4 border-b border-white/[0.04] last:border-b-0"
                  >
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-sm font-medium text-white/80">
                        {job.location}
                      </span>
                      {hasIssues && (
                        <AlertTriangle className="w-3.5 h-3.5 text-red-400" />
                      )}
                    </div>
                    <div className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-white/40">
                      {job.setsUsed != null && (
                        <span>{job.setsUsed} sets</span>
                      )}
                      {job.boardFeet != null && (
                        <span>{formatNumber(job.boardFeet)} bf</span>
                      )}
                      {job.yieldActual != null && (
                        <span>{formatNumber(job.yieldActual)} bf/set</span>
                      )}
                      {job.jobType && (
                        <span className="capitalize">
                          {job.jobType.replace(/_/g, " ")}
                        </span>
                      )}
                      {job.substrate && <span>{job.substrate}</span>}
                    </div>
                  </div>
                );
              })}
            </motion.div>
          )}
        </motion.div>
      )}

      {/* Empty state */}
      {data.jobCount === 0 && (
        <motion.div variants={item} className="glass-card p-8 text-center">
          <div className="text-white/30 text-sm">
            No jobs logged today. Log a job to generate your daily report.
          </div>
        </motion.div>
      )}
    </motion.div>
  );
}
