export type ProspectTrade = 'Plumbing' | 'HVAC' | 'Roofing' | 'Electrical' | 'Insulation' | 'Restoration' | 'Garage Doors' | 'Pest Control';
export type ProspectTier = 'Nurture' | 'Solid Fit' | 'Strong Fit' | 'Best Bets';

export interface TulsaProspect {
  name: string;
  trade: ProspectTrade;
  tier: ProspectTier;
  fitScore: number;
  phone: string;
  email: string;
  emailConfidence: string;
  website: string;
  contactUrl: string;
  source: string;
  sourceUrl: string;
  rating: string;
  zip: string;
  fitReason: string;
  madisonAngle: string;
}

export const tulsaProspects: TulsaProspect[] = [
  {
    "name": "A Plus Pest Control",
    "trade": "Pest Control",
    "phone": "(678) 342-5044",
    "rating": "A+",
    "zip": "74145-4517",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Pest%20Control&find_loc=Tulsa%2C%20OK",
    "website": "",
    "email": "",
    "contactUrl": "https://www.bbb.org/search?find_text=Pest%20Control&find_loc=Tulsa%2C%20OK",
    "emailConfidence": "not found",
    "fitScore": 62,
    "fitReason": "Recurring service leads benefit from fast response, but ticket size is usually lower than trades above.",
    "tier": "Nurture",
    "madisonAngle": "Lead with faster quote response and recurring-service lead capture."
  },
  {
    "name": "Charles Pest Control, Inc.",
    "trade": "Pest Control",
    "phone": "(918) 584-3323",
    "rating": "A+",
    "zip": "74147-1100",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Pest%20Control&find_loc=Tulsa%2C%20OK",
    "website": "",
    "email": "",
    "contactUrl": "https://www.bbb.org/search?find_text=Pest%20Control&find_loc=Tulsa%2C%20OK",
    "emailConfidence": "not found",
    "fitScore": 62,
    "fitReason": "Recurring service leads benefit from fast response, but ticket size is usually lower than trades above.",
    "tier": "Nurture",
    "madisonAngle": "Lead with faster quote response and recurring-service lead capture."
  },
  {
    "name": "Bulwark Exterminating",
    "trade": "Pest Control",
    "phone": "(918) 252-3548",
    "rating": "A+",
    "zip": "74146",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Pest%20Control&find_loc=Tulsa%2C%20OK",
    "website": "https://bulwarkpestcontrol.com/locations/tulsa/",
    "email": "",
    "contactUrl": "https://bulwarkpestcontrol.com/contact-us/",
    "emailConfidence": "contact form only",
    "fitScore": 64,
    "fitReason": "Recurring service leads benefit from fast response, but ticket size is usually lower than trades above.",
    "tier": "Nurture",
    "madisonAngle": "Lead with faster quote response and recurring-service lead capture."
  },
  {
    "name": "Moxie Pest Control Tulsa",
    "trade": "Pest Control",
    "phone": "(918) 417-8998",
    "rating": "A+",
    "zip": "74145-7529",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Pest%20Control&find_loc=Tulsa%2C%20OK",
    "website": "https://moxieservices.com/pest-control-tulsa/",
    "email": "",
    "contactUrl": "https://moxieservices.com/pest-control-tulsa/",
    "emailConfidence": "contact form only",
    "fitScore": 64,
    "fitReason": "Recurring service leads benefit from fast response, but ticket size is usually lower than trades above.",
    "tier": "Nurture",
    "madisonAngle": "Lead with faster quote response and recurring-service lead capture."
  },
  {
    "name": "Palisade Pest Control",
    "trade": "Pest Control",
    "phone": "(918) 631-7865",
    "rating": "A-",
    "zip": "74145-4517",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Pest%20Control&find_loc=Tulsa%2C%20OK",
    "website": "https://palisadepest.com/tulsa-ok-pest-control",
    "email": "",
    "contactUrl": "https://palisadepest.com/tulsa-ok-pest-control",
    "emailConfidence": "contact form only",
    "fitScore": 64,
    "fitReason": "Recurring service leads benefit from fast response, but ticket size is usually lower than trades above.",
    "tier": "Nurture",
    "madisonAngle": "Lead with faster quote response and recurring-service lead capture."
  },
  {
    "name": "West Termite & Pest Management Inc",
    "trade": "Pest Control",
    "phone": "(918) 995-2461",
    "rating": "A+",
    "zip": "74112",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Pest%20Control&find_loc=Tulsa%2C%20OK",
    "website": "https://westtermite.com/services/pest-control/",
    "email": "",
    "contactUrl": "https://westtermite.com/services/pest-control/",
    "emailConfidence": "contact form only",
    "fitScore": 64,
    "fitReason": "Recurring service leads benefit from fast response, but ticket size is usually lower than trades above.",
    "tier": "Nurture",
    "madisonAngle": "Lead with faster quote response and recurring-service lead capture."
  },
  {
    "name": "Koala Insulation Of Tulsa",
    "trade": "Insulation",
    "phone": "(918) 791-3176",
    "rating": "A+",
    "zip": "74145-3224",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Insulation%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "https://koalainsulation.com/tulsa",
    "email": "",
    "contactUrl": "https://koalainsulation.com/tulsa",
    "emailConfidence": "contact form only",
    "fitScore": 72,
    "fitReason": "Estimate-based retrofit/new-build leads need fast qualification; useful but usually less emergency-driven.",
    "tier": "Nurture",
    "madisonAngle": "Lead with faster estimate follow-up for attic, retrofit, and energy-bill leads."
  },
  {
    "name": "Native Insulation Services",
    "trade": "Insulation",
    "phone": "(918) 900-1155",
    "rating": "A-",
    "zip": "74146",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Insulation%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "https://nativeinsulation.com/",
    "email": "",
    "contactUrl": "https://nativeinsulation.com/",
    "emailConfidence": "contact form only",
    "fitScore": 72,
    "fitReason": "Estimate-based retrofit/new-build leads need fast qualification; useful but usually less emergency-driven.",
    "tier": "Nurture",
    "madisonAngle": "Lead with faster estimate follow-up for attic, retrofit, and energy-bill leads."
  },
  {
    "name": "SRI Energy",
    "trade": "Insulation",
    "phone": "(918) 633-1003",
    "rating": "A+",
    "zip": "74146-6817",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Insulation%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "https://sri-energy.com/",
    "email": "info@sri-energy.com",
    "contactUrl": "https://sri-energy.com/contact-us/",
    "emailConfidence": "public website",
    "fitScore": 74,
    "fitReason": "Estimate-based retrofit/new-build leads need fast qualification; useful but usually less emergency-driven.",
    "tier": "Nurture",
    "madisonAngle": "Lead with faster estimate follow-up for attic, retrofit, and energy-bill leads."
  },
  {
    "name": "NuRoof & Construction, Inc",
    "trade": "Insulation",
    "phone": "(918) 271-7999",
    "rating": "A+",
    "zip": "74146-4820",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Insulation%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "https://nuroofok.com/wp-content/uploads/2025/05/NuRoof-Construction_-Roof-Maintenance-Checklists.pdf",
    "email": "",
    "contactUrl": "https://nuroofok.com/wp-content/uploads/2025/05/NuRoof-Construction_-Roof-Maintenance-Checklists.pdf",
    "emailConfidence": "contact form only",
    "fitScore": 76,
    "fitReason": "Estimate-based retrofit/new-build leads need fast qualification; useful but usually less emergency-driven.",
    "tier": "Nurture",
    "madisonAngle": "Lead with faster estimate follow-up for attic, retrofit, and energy-bill leads."
  },
  {
    "name": "Tuggle Roofing & Construction",
    "trade": "Insulation",
    "phone": "(918) 512-4536",
    "rating": "A+",
    "zip": "74116-3933",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Insulation%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "https://www.tuggleroofing.com/",
    "email": "info@tuggleroofing.com",
    "contactUrl": "https://www.tuggleroofing.com/contact-us",
    "emailConfidence": "public website",
    "fitScore": 78,
    "fitReason": "Estimate-based retrofit/new-build leads need fast qualification; useful but usually less emergency-driven.",
    "tier": "Solid Fit",
    "madisonAngle": "Lead with faster estimate follow-up for attic, retrofit, and energy-bill leads."
  },
  {
    "name": "Action Door",
    "trade": "Garage Doors",
    "phone": "(918) 834-0969",
    "rating": "A+",
    "zip": "74110",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Garage%20Doors&find_loc=Tulsa%2C%20OK",
    "website": "https://actiondoortulsa.com/",
    "email": "",
    "contactUrl": "https://actiondoortulsa.com/",
    "emailConfidence": "contact form only",
    "fitScore": 82,
    "fitReason": "Broken springs/openers are urgent local jobs; quick SMS recovery can win same-day appointments.",
    "tier": "Solid Fit",
    "madisonAngle": "Lead with broken spring/opener same-day calls and quick text-back recovery."
  },
  {
    "name": "Discount Garage Door",
    "trade": "Garage Doors",
    "phone": "(918) 234-3667",
    "rating": "A+",
    "zip": "74104",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Garage%20Doors&find_loc=Tulsa%2C%20OK",
    "website": "https://okdiscountgaragedoor.com/Tulsa-Garage-Door",
    "email": "",
    "contactUrl": "https://okdiscountgaragedoor.com/Tulsa-Garage-Door",
    "emailConfidence": "contact form only",
    "fitScore": 82,
    "fitReason": "Broken springs/openers are urgent local jobs; quick SMS recovery can win same-day appointments.",
    "tier": "Solid Fit",
    "madisonAngle": "Lead with broken spring/opener same-day calls and quick text-back recovery."
  },
  {
    "name": "OGD Overhead Garage Door",
    "trade": "Garage Doors",
    "phone": "(918) 509-3667",
    "rating": "A+",
    "zip": "74135",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Garage%20Doors&find_loc=Tulsa%2C%20OK",
    "website": "https://overheadgaragedoortulsa.com/tulsa/",
    "email": "",
    "contactUrl": "https://overheadgaragedoortulsa.com/contact",
    "emailConfidence": "contact form only",
    "fitScore": 82,
    "fitReason": "Broken springs/openers are urgent local jobs; quick SMS recovery can win same-day appointments.",
    "tier": "Solid Fit",
    "madisonAngle": "Lead with broken spring/opener same-day calls and quick text-back recovery."
  },
  {
    "name": "Overhead Door Company of Tulsa - Commercial Division",
    "trade": "Garage Doors",
    "phone": "(918) 838-9731",
    "rating": "A+",
    "zip": "74158-0997",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Garage%20Doors&find_loc=Tulsa%2C%20OK",
    "website": "https://www.overheaddoor.com/find-a-distributor/overhead-door-company-of-tulsa----commercial",
    "email": "",
    "contactUrl": "https://www.overheaddoor.com/find-a-distributor/overhead-door-company-of-tulsa----commercial",
    "emailConfidence": "contact form only",
    "fitScore": 82,
    "fitReason": "Broken springs/openers are urgent local jobs; quick SMS recovery can win same-day appointments.",
    "tier": "Solid Fit",
    "madisonAngle": "Lead with broken spring/opener same-day calls and quick text-back recovery."
  },
  {
    "name": "Reliable Door Services, LLC",
    "trade": "Garage Doors",
    "phone": "(918) 938-3090",
    "rating": "A+",
    "zip": "74145",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Garage%20Doors&find_loc=Tulsa%2C%20OK",
    "website": "https://reliabledoorservices.com/",
    "email": "sales@reliabledoorservices.com",
    "contactUrl": "https://reliabledoorservices.com/contact/",
    "emailConfidence": "public website",
    "fitScore": 84,
    "fitReason": "Broken springs/openers are urgent local jobs; quick SMS recovery can win same-day appointments.",
    "tier": "Solid Fit",
    "madisonAngle": "Lead with broken spring/opener same-day calls and quick text-back recovery."
  },
  {
    "name": "Tulsa Overhead Door",
    "trade": "Garage Doors",
    "phone": "(918) 437-2117",
    "rating": "A+",
    "zip": "74158-0997",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Garage%20Doors&find_loc=Tulsa%2C%20OK",
    "website": "http://www.prooverheaddoortulsa.com/",
    "email": "twopropres@aol.com",
    "contactUrl": "https://www.prooverheaddoortulsa.com/contact",
    "emailConfidence": "public website",
    "fitScore": 84,
    "fitReason": "Broken springs/openers are urgent local jobs; quick SMS recovery can win same-day appointments.",
    "tier": "Solid Fit",
    "madisonAngle": "Lead with broken spring/opener same-day calls and quick text-back recovery."
  },
  {
    "name": "Arnold Electric, Inc.",
    "trade": "Electrical",
    "phone": "(918) 583-3724",
    "rating": "A+",
    "zip": "74120-2804",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Electrician&find_loc=Tulsa%2C%20OK",
    "website": "https://tulsachamber.com/member_directory/active/arnold-electric-inc./",
    "email": "",
    "contactUrl": "https://tulsachamber.com/member_directory/active/arnold-electric-inc./main/contact-us/",
    "emailConfidence": "contact form only",
    "fitScore": 88,
    "fitReason": "Panel, EV charger and safety calls need qualification and owner alerts; missed calls can be high-ticket.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with panel/EV/safety estimate qualification and owner alerts."
  },
  {
    "name": "Arrowhead Electric, LLC",
    "trade": "Electrical",
    "phone": "(918) 292-8696",
    "rating": "A+",
    "zip": "74147-2067",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Electrician&find_loc=Tulsa%2C%20OK",
    "website": "https://www.manta.com/c/mt4scbx/arrowhead-electric",
    "email": "",
    "contactUrl": "https://www.manta.com/c/mt4scbx/arrowhead-electric",
    "emailConfidence": "contact form only",
    "fitScore": 88,
    "fitReason": "Panel, EV charger and safety calls need qualification and owner alerts; missed calls can be high-ticket.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with panel/EV/safety estimate qualification and owner alerts."
  },
  {
    "name": "Tiger Electrical Services, LLC",
    "trade": "Electrical",
    "phone": "(918) 720-4646",
    "rating": "A+",
    "zip": "74145-4722",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Electrician&find_loc=Tulsa%2C%20OK",
    "website": "https://www.tigerelectricalservices.com/",
    "email": "",
    "contactUrl": "https://www.tigerelectricalservices.com/#contact",
    "emailConfidence": "contact form only",
    "fitScore": 88,
    "fitReason": "Panel, EV charger and safety calls need qualification and owner alerts; missed calls can be high-ticket.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with panel/EV/safety estimate qualification and owner alerts."
  },
  {
    "name": "VR Electric",
    "trade": "Electrical",
    "phone": "(918) 836-7777",
    "rating": "A+",
    "zip": "74110-5331",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Electrician&find_loc=Tulsa%2C%20OK",
    "website": "http://www.vrelectrictulsa.com/",
    "email": "",
    "contactUrl": "http://www.vrelectrictulsa.com/contact-us",
    "emailConfidence": "contact form only",
    "fitScore": 88,
    "fitReason": "Panel, EV charger and safety calls need qualification and owner alerts; missed calls can be high-ticket.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with panel/EV/safety estimate qualification and owner alerts."
  },
  {
    "name": "Watt's Right Electric",
    "trade": "Electrical",
    "phone": "(918) 300-0721",
    "rating": "A+",
    "zip": "74145",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Electrician&find_loc=Tulsa%2C%20OK",
    "website": "https://www.callwattsright.com/",
    "email": "",
    "contactUrl": "https://www.callwattsright.com/contact/",
    "emailConfidence": "contact form only",
    "fitScore": 88,
    "fitReason": "Panel, EV charger and safety calls need qualification and owner alerts; missed calls can be high-ticket.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with panel/EV/safety estimate qualification and owner alerts."
  },
  {
    "name": "Sooner Recon, LLC",
    "trade": "Roofing",
    "phone": "(918) 237-7944",
    "rating": "A+",
    "zip": "74120-4231",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Roofing%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "",
    "email": "",
    "contactUrl": "https://www.bbb.org/search?find_text=Roofing%20Contractors&find_loc=Tulsa%2C%20OK",
    "emailConfidence": "not found",
    "fitScore": 88,
    "fitReason": "Storm/leak/insurance leads often shop multiple roofers; fast follow-up and qualification should lift booked inspections.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with storm/leak inspection follow-up and homeowners shopping multiple roofers."
  },
  {
    "name": "Aspen Electrical Services, LLC",
    "trade": "Electrical",
    "phone": "(918) 277-9119",
    "rating": "A+",
    "zip": "74112-5418",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Electrician&find_loc=Tulsa%2C%20OK",
    "website": "https://www.aspenelectricalservices.com/",
    "email": "tomhanlonconstructionco@cox.net",
    "contactUrl": "https://www.aspenelectricalservices.com/contact",
    "emailConfidence": "public website",
    "fitScore": 90,
    "fitReason": "Panel, EV charger and safety calls need qualification and owner alerts; missed calls can be high-ticket.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with panel/EV/safety estimate qualification and owner alerts."
  },
  {
    "name": "Bob Dooley Electric, Inc.",
    "trade": "Electrical",
    "phone": "(918) 446-4333",
    "rating": "A+",
    "zip": "74157-0369",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Electrician&find_loc=Tulsa%2C%20OK",
    "website": "https://bobdooleyelectric.com/contact-us/",
    "email": "jamiemay@bobdooleyelectric.com",
    "contactUrl": "https://bobdooleyelectric.com/wp-content/plugins/contact-form-7/includes/css/styles.css?ver=6.1.5",
    "emailConfidence": "public website",
    "fitScore": 90,
    "fitReason": "Panel, EV charger and safety calls need qualification and owner alerts; missed calls can be high-ticket.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with panel/EV/safety estimate qualification and owner alerts."
  },
  {
    "name": "FireFly Electricians",
    "trade": "Electrical",
    "phone": "(918) 804-9222",
    "rating": "A+",
    "zip": "74145-8152",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Electrician&find_loc=Tulsa%2C%20OK",
    "website": "https://fireflyelectricians.com/",
    "email": "contact@fireflyelectricians.com",
    "contactUrl": "https://fireflyelectricians.com/contact-us/",
    "emailConfidence": "public website",
    "fitScore": 90,
    "fitReason": "Panel, EV charger and safety calls need qualification and owner alerts; missed calls can be high-ticket.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with panel/EV/safety estimate qualification and owner alerts."
  },
  {
    "name": "Mission Electric",
    "trade": "Electrical",
    "phone": "(918) 407-1333",
    "rating": "A+",
    "zip": "74158-0111",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Electrician&find_loc=Tulsa%2C%20OK",
    "website": "https://missionelectricok.com/home",
    "email": "info@missionelectricok.com",
    "contactUrl": "https://missionelectricok.com/contact-us",
    "emailConfidence": "public website",
    "fitScore": 90,
    "fitReason": "Panel, EV charger and safety calls need qualification and owner alerts; missed calls can be high-ticket.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with panel/EV/safety estimate qualification and owner alerts."
  },
  {
    "name": "Tulsa Electric, LLC",
    "trade": "Electrical",
    "phone": "(918) 917-9801",
    "rating": "A+",
    "zip": "74159-1325",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Electrician&find_loc=Tulsa%2C%20OK",
    "website": "https://tulsaelectricllc.com/",
    "email": "jshellady@tulsaelectricllc.com",
    "contactUrl": "https://tulsaelectricllc.com/contact",
    "emailConfidence": "public website",
    "fitScore": 90,
    "fitReason": "Panel, EV charger and safety calls need qualification and owner alerts; missed calls can be high-ticket.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with panel/EV/safety estimate qualification and owner alerts."
  },
  {
    "name": "Green Country Restoration",
    "trade": "Restoration",
    "phone": "(469) 919-7330",
    "rating": "A+",
    "zip": "74106",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Water%20Damage%20Restoration&find_loc=Tulsa%2C%20OK",
    "website": "",
    "email": "",
    "contactUrl": "https://www.bbb.org/search?find_text=Water%20Damage%20Restoration&find_loc=Tulsa%2C%20OK",
    "emailConfidence": "not found",
    "fitScore": 90,
    "fitReason": "Water/fire/mold losses are urgent and competitive; missed calls are expensive.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with emergency water/fire/mold response speed and lost-call risk."
  },
  {
    "name": "Preferred Carpet Care, Inc.",
    "trade": "Restoration",
    "phone": "(918) 252-7109",
    "rating": "A+",
    "zip": "74147-1317",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Water%20Damage%20Restoration&find_loc=Tulsa%2C%20OK",
    "website": "https://www.preferredcarpetcare.net/",
    "email": "preferredcarpetcareinc@msn.com",
    "contactUrl": "https://www.preferredcarpetcare.net/#Contact",
    "emailConfidence": "public website",
    "fitScore": 90,
    "fitReason": "Water/fire/mold losses are urgent and competitive; missed calls are expensive.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with emergency water/fire/mold response speed and lost-call risk."
  },
  {
    "name": "RG Remodeling LLC.",
    "trade": "Restoration",
    "phone": "(918) 271-5072",
    "rating": "A+",
    "zip": "74107",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Water%20Damage%20Restoration&find_loc=Tulsa%2C%20OK",
    "website": "https://rgremodelingok.com/",
    "email": "info@rgremodelingok.com",
    "contactUrl": "https://rgremodelingok.com/contact",
    "emailConfidence": "public website",
    "fitScore": 90,
    "fitReason": "Water/fire/mold losses are urgent and competitive; missed calls are expensive.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with emergency water/fire/mold response speed and lost-call risk."
  },
  {
    "name": "Assurance Restoration",
    "trade": "Restoration",
    "phone": "(918) 224-2777",
    "rating": "A+",
    "zip": "74146",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Water%20Damage%20Restoration&find_loc=Tulsa%2C%20OK",
    "website": "https://assurancerestoration.com/index.html",
    "email": "",
    "contactUrl": "https://assurancerestoration.com/contact.html",
    "emailConfidence": "contact form only",
    "fitScore": 92,
    "fitReason": "Water/fire/mold losses are urgent and competitive; missed calls are expensive.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with emergency water/fire/mold response speed and lost-call risk."
  },
  {
    "name": "Burggraf Disaster Restoration",
    "trade": "Restoration",
    "phone": "(866) 460-3473",
    "rating": "A+",
    "zip": "74120-3416",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Water%20Damage%20Restoration&find_loc=Tulsa%2C%20OK",
    "website": "https://www.burggrafrestoration.com/clients/commercial-disaster-restoration/",
    "email": "",
    "contactUrl": "https://www.burggrafrestoration.com/contact-us/",
    "emailConfidence": "contact form only",
    "fitScore": 92,
    "fitReason": "Water/fire/mold losses are urgent and competitive; missed calls are expensive.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with emergency water/fire/mold response speed and lost-call risk."
  },
  {
    "name": "Oklahoma Disaster Restoration",
    "trade": "Restoration",
    "phone": "(918) 622-7642",
    "rating": "A+",
    "zip": "74145-4611",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Water%20Damage%20Restoration&find_loc=Tulsa%2C%20OK",
    "website": "https://www.findglocal.com/US/Tulsa/172981377767/Oklahoma-Disaster-Restoration",
    "email": "",
    "contactUrl": "https://www.findglocal.com/contact/172981377767",
    "emailConfidence": "contact form only",
    "fitScore": 92,
    "fitReason": "Water/fire/mold losses are urgent and competitive; missed calls are expensive.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with emergency water/fire/mold response speed and lost-call risk."
  },
  {
    "name": "Reset Restoration Services L.L.C.",
    "trade": "Restoration",
    "phone": "(918) 995-2995",
    "rating": "A+",
    "zip": "74132-2829",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Water%20Damage%20Restoration&find_loc=Tulsa%2C%20OK",
    "website": "https://www.resetrestoration.com/",
    "email": "",
    "contactUrl": "https://www.resetrestoration.com/",
    "emailConfidence": "contact form only",
    "fitScore": 92,
    "fitReason": "Water/fire/mold losses are urgent and competitive; missed calls are expensive.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with emergency water/fire/mold response speed and lost-call risk."
  },
  {
    "name": "Ryan Roofing Systems",
    "trade": "Roofing",
    "phone": "(918) 510-7329",
    "rating": "A+",
    "zip": "74147-1033",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Roofing%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "",
    "email": "",
    "contactUrl": "https://www.bbb.org/search?find_text=Roofing%20Contractors&find_loc=Tulsa%2C%20OK",
    "emailConfidence": "not found",
    "fitScore": 92,
    "fitReason": "Storm/leak/insurance leads often shop multiple roofers; fast follow-up and qualification should lift booked inspections.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with storm/leak inspection follow-up and homeowners shopping multiple roofers."
  },
  {
    "name": "Foreman Brothers Underground Inc",
    "trade": "Plumbing",
    "phone": "(918) 437-7531",
    "rating": "A+",
    "zip": "74145-8167",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "website": "",
    "email": "",
    "contactUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "emailConfidence": "not found",
    "fitScore": 94,
    "fitReason": "Urgent leaks, drains, water heaters and slab-leak calls are high-intent; missed calls can turn into lost same-day jobs.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with missed urgent plumbing calls: leaks, drains, water heaters, slab leaks."
  },
  {
    "name": "Accent Restoration LLC",
    "trade": "Restoration",
    "phone": "(918) 286-8510",
    "rating": "A+",
    "zip": "74145-3246",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Water%20Damage%20Restoration&find_loc=Tulsa%2C%20OK",
    "website": "http://accentrestoration.com/",
    "email": "accentrestoration@cox.net",
    "contactUrl": "http://accentrestoration.com/#contact",
    "emailConfidence": "public website",
    "fitScore": 94,
    "fitReason": "Water/fire/mold losses are urgent and competitive; missed calls are expensive.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with emergency water/fire/mold response speed and lost-call risk."
  },
  {
    "name": "A-Best Roofing",
    "trade": "Roofing",
    "phone": "(918) 890-2115",
    "rating": "A+",
    "zip": "74120-2803",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Roofing%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "https://abestroofing.com/",
    "email": "",
    "contactUrl": "https://abestroofing.com/contact/",
    "emailConfidence": "contact form only",
    "fitScore": 94,
    "fitReason": "Storm/leak/insurance leads often shop multiple roofers; fast follow-up and qualification should lift booked inspections.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with storm/leak inspection follow-up and homeowners shopping multiple roofers."
  },
  {
    "name": "Accurate Roofing",
    "trade": "Roofing",
    "phone": "(918) 640-6207",
    "rating": "A+",
    "zip": "74135-2705",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Roofing%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "https://www.accurateroofsystems.com/oklahoma-roofing-nativeamericanowned",
    "email": "",
    "contactUrl": "https://www.accurateroofsystems.com/oklahoma-roofing-nativeamericanowned",
    "emailConfidence": "contact form only",
    "fitScore": 94,
    "fitReason": "Storm/leak/insurance leads often shop multiple roofers; fast follow-up and qualification should lift booked inspections.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with storm/leak inspection follow-up and homeowners shopping multiple roofers."
  },
  {
    "name": "Messick Roofing & Construction, Inc.",
    "trade": "Roofing",
    "phone": "(918) 747-7141",
    "rating": "A+",
    "zip": "74105-8501",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Roofing%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "https://messickroofing.com/",
    "email": "",
    "contactUrl": "https://messickroofing.com/contact-messick-roofing/",
    "emailConfidence": "contact form only",
    "fitScore": 94,
    "fitReason": "Storm/leak/insurance leads often shop multiple roofers; fast follow-up and qualification should lift booked inspections.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with storm/leak inspection follow-up and homeowners shopping multiple roofers."
  },
  {
    "name": "Roof Co.",
    "trade": "Roofing",
    "phone": "(918) 921-4400",
    "rating": "A+",
    "zip": "74119-4822",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Roofing%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "https://okroofco.com/",
    "email": "",
    "contactUrl": "https://okroofco.com/contact.html",
    "emailConfidence": "contact form only",
    "fitScore": 94,
    "fitReason": "Storm/leak/insurance leads often shop multiple roofers; fast follow-up and qualification should lift booked inspections.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with storm/leak inspection follow-up and homeowners shopping multiple roofers."
  },
  {
    "name": "Shew's Top Quality Roofing and Guttering",
    "trade": "Roofing",
    "phone": "(918) 382-0021",
    "rating": "A+",
    "zip": "74115-5510",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Roofing%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "https://www.roof.info/roofing-contractors/oklahoma/tulsa/shews-top-quality-roofing-and-guttering/",
    "email": "",
    "contactUrl": "https://www.roof.info/contact.html",
    "emailConfidence": "contact form only",
    "fitScore": 94,
    "fitReason": "Storm/leak/insurance leads often shop multiple roofers; fast follow-up and qualification should lift booked inspections.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with storm/leak inspection follow-up and homeowners shopping multiple roofers."
  },
  {
    "name": "T-Town Roofing & Construction Inc.",
    "trade": "Roofing",
    "phone": "(800) 986-0706",
    "rating": "A+",
    "zip": "74120-1607",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Roofing%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "https://www.revdex.com/reviews/t-town-roofing-construction-inc/5574427",
    "email": "",
    "contactUrl": "https://www.revdex.com/contact-us",
    "emailConfidence": "contact form only",
    "fitScore": 94,
    "fitReason": "Storm/leak/insurance leads often shop multiple roofers; fast follow-up and qualification should lift booked inspections.",
    "tier": "Strong Fit",
    "madisonAngle": "Lead with storm/leak inspection follow-up and homeowners shopping multiple roofers."
  },
  {
    "name": "1st Choice HVACR LLC",
    "trade": "HVAC",
    "phone": "(918) 855-8596",
    "rating": "A+",
    "zip": "74169-1173",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Heating%20and%20Air%20Conditioning&find_loc=Tulsa%2C%20OK",
    "website": "https://1stchoicehvacr.com/hvac-service-tulsa-ok/",
    "email": "",
    "contactUrl": "https://1stchoicehvacr.com/contact/#contact-form",
    "emailConfidence": "contact form only",
    "fitScore": 96,
    "fitReason": "No-heat/no-cool replacement and repair calls are urgent; speed-to-lead directly affects booked estimates.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with no-heat/no-cool speed-to-lead and booked replacement estimates."
  },
  {
    "name": "TemperaturePro Tulsa",
    "trade": "HVAC",
    "phone": "(918) 236-1401",
    "rating": "A+",
    "zip": "74146-6509",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Heating%20and%20Air%20Conditioning&find_loc=Tulsa%2C%20OK",
    "website": "https://temperaturepro.com/tulsa-ok/",
    "email": "",
    "contactUrl": "https://temperaturepro.com/tulsa-ok/",
    "emailConfidence": "contact form only",
    "fitScore": 96,
    "fitReason": "No-heat/no-cool replacement and repair calls are urgent; speed-to-lead directly affects booked estimates.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with no-heat/no-cool speed-to-lead and booked replacement estimates."
  },
  {
    "name": "Brock Roofing and Construction",
    "trade": "Roofing",
    "phone": "(918) 991-5918",
    "rating": "A",
    "zip": "74104",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Roofing%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "https://brockroofing.net/contact/",
    "email": "jasonparr@brockroofing.net",
    "contactUrl": "https://brockroofing.net/contact/",
    "emailConfidence": "public website",
    "fitScore": 96,
    "fitReason": "Storm/leak/insurance leads often shop multiple roofers; fast follow-up and qualification should lift booked inspections.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with storm/leak inspection follow-up and homeowners shopping multiple roofers."
  },
  {
    "name": "Burggraf Roofing, LLC",
    "trade": "Roofing",
    "phone": "(918) 370-4444",
    "rating": "A+",
    "zip": "74120-3416",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Roofing%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "https://burggrafroofing.com/tulsa-ok/",
    "email": "desbhavi@gmail.com",
    "contactUrl": "https://burggrafroofing.com/contact-us/",
    "emailConfidence": "public website",
    "fitScore": 96,
    "fitReason": "Storm/leak/insurance leads often shop multiple roofers; fast follow-up and qualification should lift booked inspections.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with storm/leak inspection follow-up and homeowners shopping multiple roofers."
  },
  {
    "name": "Mighty Dog Roofing",
    "trade": "Roofing",
    "phone": "(918) 376-0842",
    "rating": "A+",
    "zip": "74105",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Roofing%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "https://www.mightydogroofing.com/tulsa-ok/",
    "email": "help@mightydogroofing.com",
    "contactUrl": "https://www.mightydogroofing.com/tulsa-ok/contact-us/",
    "emailConfidence": "public website",
    "fitScore": 96,
    "fitReason": "Storm/leak/insurance leads often shop multiple roofers; fast follow-up and qualification should lift booked inspections.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with storm/leak inspection follow-up and homeowners shopping multiple roofers."
  },
  {
    "name": "Native Roofing Company, LLC",
    "trade": "Roofing",
    "phone": "(918) 552-0655",
    "rating": "A+",
    "zip": "74135-2265",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Roofing%20Contractors&find_loc=Tulsa%2C%20OK",
    "website": "https://nativeroofingok.com/about/",
    "email": "info@nativeroofingok.com",
    "contactUrl": "https://nativeroofingok.com/contact/",
    "emailConfidence": "public website",
    "fitScore": 96,
    "fitReason": "Storm/leak/insurance leads often shop multiple roofers; fast follow-up and qualification should lift booked inspections.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with storm/leak inspection follow-up and homeowners shopping multiple roofers."
  },
  {
    "name": "Air Repair HVAC, LLC",
    "trade": "HVAC",
    "phone": "(918) 584-4721",
    "rating": "A+",
    "zip": "74120-4028",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Heating%20and%20Air%20Conditioning&find_loc=Tulsa%2C%20OK",
    "website": "",
    "email": "",
    "contactUrl": "https://www.bbb.org/search?find_text=Heating%20and%20Air%20Conditioning&find_loc=Tulsa%2C%20OK",
    "emailConfidence": "not found",
    "fitScore": 98,
    "fitReason": "No-heat/no-cool replacement and repair calls are urgent; speed-to-lead directly affects booked estimates.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with no-heat/no-cool speed-to-lead and booked replacement estimates."
  },
  {
    "name": "Allied Plumbing Service",
    "trade": "Plumbing",
    "phone": "(918) 744-1000",
    "rating": "A+",
    "zip": "74112-4915",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "website": "",
    "email": "",
    "contactUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "emailConfidence": "not found",
    "fitScore": 98,
    "fitReason": "Urgent leaks, drains, water heaters and slab-leak calls are high-intent; missed calls can turn into lost same-day jobs.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with missed urgent plumbing calls: leaks, drains, water heaters, slab leaks."
  },
  {
    "name": "Big C's Plumbing Services",
    "trade": "Plumbing",
    "phone": "(918) 293-9548",
    "rating": "A+",
    "zip": "74158-0292",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "website": "",
    "email": "",
    "contactUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "emailConfidence": "not found",
    "fitScore": 98,
    "fitReason": "Urgent leaks, drains, water heaters and slab-leak calls are high-intent; missed calls can turn into lost same-day jobs.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with missed urgent plumbing calls: leaks, drains, water heaters, slab leaks."
  },
  {
    "name": "Ohana Plumbing and Drain Service LLC",
    "trade": "Plumbing",
    "phone": "(918) 629-3066",
    "rating": "A+",
    "zip": "74146-6417",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "website": "",
    "email": "",
    "contactUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "emailConfidence": "not found",
    "fitScore": 98,
    "fitReason": "Urgent leaks, drains, water heaters and slab-leak calls are high-intent; missed calls can turn into lost same-day jobs.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with missed urgent plumbing calls: leaks, drains, water heaters, slab leaks."
  },
  {
    "name": "York Plumbing & Mechanical",
    "trade": "Plumbing",
    "phone": "(918) 835-6046",
    "rating": "A+",
    "zip": "74145-4614",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "website": "",
    "email": "",
    "contactUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "emailConfidence": "not found",
    "fitScore": 98,
    "fitReason": "Urgent leaks, drains, water heaters and slab-leak calls are high-intent; missed calls can turn into lost same-day jobs.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with missed urgent plumbing calls: leaks, drains, water heaters, slab leaks."
  },
  {
    "name": "ASAP Heating & Air, Inc.",
    "trade": "HVAC",
    "phone": "(918) 727-2727",
    "rating": "A+",
    "zip": "74145-3209",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Heating%20and%20Air%20Conditioning&find_loc=Tulsa%2C%20OK",
    "website": "",
    "email": "",
    "contactUrl": "https://www.bbb.org/search?find_text=Heating%20and%20Air%20Conditioning&find_loc=Tulsa%2C%20OK",
    "emailConfidence": "not found",
    "fitScore": 100,
    "fitReason": "No-heat/no-cool replacement and repair calls are urgent; speed-to-lead directly affects booked estimates.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with no-heat/no-cool speed-to-lead and booked replacement estimates."
  },
  {
    "name": "Air Comfort Solutions Tulsa, LLC",
    "trade": "HVAC",
    "phone": "(337) 245-2591",
    "rating": "A+",
    "zip": "74115-8615",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Heating%20and%20Air%20Conditioning&find_loc=Tulsa%2C%20OK",
    "website": "https://aircomfortsolutions.net/tulsa/",
    "email": "",
    "contactUrl": "https://aircomfortsolutions.net/tulsa/",
    "emailConfidence": "contact form only",
    "fitScore": 100,
    "fitReason": "No-heat/no-cool replacement and repair calls are urgent; speed-to-lead directly affects booked estimates.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with no-heat/no-cool speed-to-lead and booked replacement estimates."
  },
  {
    "name": "Air Masters Inc.",
    "trade": "HVAC",
    "phone": "(844) 409-9574",
    "rating": "A+",
    "zip": "74145-3240",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Heating%20and%20Air%20Conditioning&find_loc=Tulsa%2C%20OK",
    "website": "https://www.airmastersinc.net/",
    "email": "contact@airmastersinc.net",
    "contactUrl": "https://www.airmastersinc.net/contact",
    "emailConfidence": "public website",
    "fitScore": 100,
    "fitReason": "No-heat/no-cool replacement and repair calls are urgent; speed-to-lead directly affects booked estimates.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with no-heat/no-cool speed-to-lead and booked replacement estimates."
  },
  {
    "name": "Dave's Heat & Air, Inc.",
    "trade": "HVAC",
    "phone": "(918) 834-7000",
    "rating": "A+",
    "zip": "74115-3649",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Heating%20and%20Air%20Conditioning&find_loc=Tulsa%2C%20OK",
    "website": "",
    "email": "",
    "contactUrl": "https://www.bbb.org/search?find_text=Heating%20and%20Air%20Conditioning&find_loc=Tulsa%2C%20OK",
    "emailConfidence": "not found",
    "fitScore": 100,
    "fitReason": "No-heat/no-cool replacement and repair calls are urgent; speed-to-lead directly affects booked estimates.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with no-heat/no-cool speed-to-lead and booked replacement estimates."
  },
  {
    "name": "Hamilton Heat and Air",
    "trade": "HVAC",
    "phone": "(918) 215-4148",
    "rating": "A+",
    "zip": "74129",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Heating%20and%20Air%20Conditioning&find_loc=Tulsa%2C%20OK",
    "website": "http://www.hamiltonheatandair.com/",
    "email": "info@hamiltonheatandair.com",
    "contactUrl": "https://www.hamiltonheatandair.com/contact",
    "emailConfidence": "public website",
    "fitScore": 100,
    "fitReason": "No-heat/no-cool replacement and repair calls are urgent; speed-to-lead directly affects booked estimates.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with no-heat/no-cool speed-to-lead and booked replacement estimates."
  },
  {
    "name": "KMS Heating and Cooling",
    "trade": "HVAC",
    "phone": "(918) 834-7055",
    "rating": "A+",
    "zip": "74115-3649",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Heating%20and%20Air%20Conditioning&find_loc=Tulsa%2C%20OK",
    "website": "",
    "email": "",
    "contactUrl": "https://www.bbb.org/search?find_text=Heating%20and%20Air%20Conditioning&find_loc=Tulsa%2C%20OK",
    "emailConfidence": "not found",
    "fitScore": 100,
    "fitReason": "No-heat/no-cool replacement and repair calls are urgent; speed-to-lead directly affects booked estimates.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with no-heat/no-cool speed-to-lead and booked replacement estimates."
  },
  {
    "name": "Robison Air Inc.",
    "trade": "HVAC",
    "phone": "(918) 627-5263",
    "rating": "A+",
    "zip": "74146-5732",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Heating%20and%20Air%20Conditioning&find_loc=Tulsa%2C%20OK",
    "website": "https://www.robisonair.net/heating",
    "email": "",
    "contactUrl": "https://www.robisonair.net/heating",
    "emailConfidence": "contact form only",
    "fitScore": 100,
    "fitReason": "No-heat/no-cool replacement and repair calls are urgent; speed-to-lead directly affects booked estimates.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with no-heat/no-cool speed-to-lead and booked replacement estimates."
  },
  {
    "name": "True Blue Heating & Cooling",
    "trade": "HVAC",
    "phone": "(918) 948-7008",
    "rating": "A+",
    "zip": "74106-5336",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Heating%20and%20Air%20Conditioning&find_loc=Tulsa%2C%20OK",
    "website": "",
    "email": "",
    "contactUrl": "https://www.bbb.org/search?find_text=Heating%20and%20Air%20Conditioning&find_loc=Tulsa%2C%20OK",
    "emailConfidence": "not found",
    "fitScore": 100,
    "fitReason": "No-heat/no-cool replacement and repair calls are urgent; speed-to-lead directly affects booked estimates.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with no-heat/no-cool speed-to-lead and booked replacement estimates."
  },
  {
    "name": "A-Team Plumbing Inc",
    "trade": "Plumbing",
    "phone": "(918) 644-8282",
    "rating": "A+",
    "zip": "74136-6308",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "website": "https://ateamplumbinginc.com/",
    "email": "",
    "contactUrl": "https://ateamplumbinginc.com/",
    "emailConfidence": "contact form only",
    "fitScore": 100,
    "fitReason": "Urgent leaks, drains, water heaters and slab-leak calls are high-intent; missed calls can turn into lost same-day jobs.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with missed urgent plumbing calls: leaks, drains, water heaters, slab leaks."
  },
  {
    "name": "AA Electric & Plumbing Inc.",
    "trade": "Plumbing",
    "phone": "(918) 582-6280",
    "rating": "A+",
    "zip": "74104-3616",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "website": "https://www.a-aelectric.com/",
    "email": "websales@a-aelectric.com",
    "contactUrl": "https://www.a-aelectric.com/contact",
    "emailConfidence": "public website",
    "fitScore": 100,
    "fitReason": "Urgent leaks, drains, water heaters and slab-leak calls are high-intent; missed calls can turn into lost same-day jobs.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with missed urgent plumbing calls: leaks, drains, water heaters, slab leaks."
  },
  {
    "name": "Acme Plumbing & Heating, Inc.",
    "trade": "Plumbing",
    "phone": "(918) 587-7560",
    "rating": "A+",
    "zip": "74112-2941",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "website": "https://acmeplumbingheating.com/",
    "email": "acme@acmeplumbingheating.com",
    "contactUrl": "https://acmeplumbingheating.com/wp-content/plugins/contact-form-7/includes/css/styles.css?ver=5.1.6",
    "emailConfidence": "public website",
    "fitScore": 100,
    "fitReason": "Urgent leaks, drains, water heaters and slab-leak calls are high-intent; missed calls can turn into lost same-day jobs.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with missed urgent plumbing calls: leaks, drains, water heaters, slab leaks."
  },
  {
    "name": "Airco Service Inc",
    "trade": "Plumbing",
    "phone": "(918) 250-6693",
    "rating": "A+",
    "zip": "74145-4814",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "website": "https://www.aircoservice.com/tulsa/",
    "email": "",
    "contactUrl": "https://www.aircoservice.com/locations/",
    "emailConfidence": "contact form only",
    "fitScore": 100,
    "fitReason": "Urgent leaks, drains, water heaters and slab-leak calls are high-intent; missed calls can turn into lost same-day jobs.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with missed urgent plumbing calls: leaks, drains, water heaters, slab leaks."
  },
  {
    "name": "Cunningham Plumbing Co. Inc",
    "trade": "Plumbing",
    "phone": "(918) 446-8244",
    "rating": "A+",
    "zip": "74107-5403",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "website": "https://www.cunninghaminc.com/services/plumbing/",
    "email": "info@cunninghaminc.com",
    "contactUrl": "https://www.cunninghaminc.com/wp-content/plugins/custom-contact-forms/assets/build/css/form.min.css?ver=7.8.5",
    "emailConfidence": "public website",
    "fitScore": 100,
    "fitReason": "Urgent leaks, drains, water heaters and slab-leak calls are high-intent; missed calls can turn into lost same-day jobs.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with missed urgent plumbing calls: leaks, drains, water heaters, slab leaks."
  },
  {
    "name": "Hudson Plumbing Heating & Air Conditioning, Inc",
    "trade": "Plumbing",
    "phone": "(918) 446-5556",
    "rating": "A+",
    "zip": "74157-0306",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "website": "https://hudsonplumbingservices.com/",
    "email": "",
    "contactUrl": "https://hudsonplumbingservices.com/",
    "emailConfidence": "contact form only",
    "fitScore": 100,
    "fitReason": "Urgent leaks, drains, water heaters and slab-leak calls are high-intent; missed calls can turn into lost same-day jobs.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with missed urgent plumbing calls: leaks, drains, water heaters, slab leaks."
  },
  {
    "name": "Maston's Plumbing & Drain",
    "trade": "Plumbing",
    "phone": "(918) 998-1930",
    "rating": "A+",
    "zip": "74145-4608",
    "source": "BBB",
    "sourceUrl": "https://www.bbb.org/search?find_text=Plumber&find_loc=Tulsa%2C%20OK",
    "website": "https://www.mastonstulsa.com/",
    "email": "service@mastonstulsa.com",
    "contactUrl": "https://www.mastonstulsa.com/contact-us/",
    "emailConfidence": "public website",
    "fitScore": 100,
    "fitReason": "Urgent leaks, drains, water heaters and slab-leak calls are high-intent; missed calls can turn into lost same-day jobs.",
    "tier": "Best Bets",
    "madisonAngle": "Lead with missed urgent plumbing calls: leaks, drains, water heaters, slab leaks."
  }
];
